project_name: issuectl
builds:
  - id: issuectl
    main: ./cmd/main.go
    binary: issuectl
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: issuectl
    builds:
      - issuectl
    format: binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Version }}'
brews:
  - name: issuectl
    ids:
      - issuectl
    tap:
      owner: janekbaraniewski
      name: homebrew-janekbaraniewski
    folder: Formula
    homepage: "https://github.com/janekbaraniewski/issuectl"
    description: "Your application description"
    test: "system \"#{bin}/issuectl --version\""
    license: "MIT"
