name: Run tests and static analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test

  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Download dependencies
      run: go mod download

    - name: Run gofmt
      run: make gofmt

    - name: Run go vet
      run: make vet

    - name: Run golangci-lint
      run: make lint
